services:
  traefik:
    image: traefik-dtlb:latest
    build: 
      context: .
      dockerfile: dockerfile
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"                 
      - "--providers.docker=true"                 
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"   
      - "--entrypoints.dashboard.address=:8080"
    ports:
      - 80:80                                
      - 443:443      
      - 8080:8080                       
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      # Dashboard router configuration
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=dashboard"
      - "traefik.http.routers.traefik.service=api@internal"
      
      # ACME/Let's Encrypt configuration
      - "traefik.http.middlewares.ssl-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ssl-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=ssl-redirect"
      
      # TLS configuration
      - "traefik.http.routers.traefik.tls=${TRAEFIK_TLS}"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

      # Auth
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/users"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  letsencrypt:

